### ISSUE TITLE
City Service

### ISSUE THREAD

**Issue by ItsCurstin** [CurstinJR/school-management-grp33#21]
- Save operation.
- Read one operation.
- Delete operation which returns nothing.
- Read all operations.
- Use of generic interface
- Use of domain-specific interface

**Comment by ItsCurstin** [comment]
Please take a look at question 6 as well.

- [ ] Q6. Implement a service to retrieve all employee name(s) living in a particular city. The formal parameter passed is the cityId.

**Comment by Niyonzima10** [comment]
Ok

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
