### ISSUE TITLE
Name & Address Factory

### ISSUE THREAD

**Issue by ItsCurstin** [CurstinJR/school-management-grp33#6]
Implement factory pattern

**Comment by ItsCurstin** [comment]
Hi Kevin, the middle name can be left empty. You need to change this to `StringUtility.setEmptyIfNull(middleName);`

https://github.com/CurstinJR/school-management-grp33/blob/5b01d1d7b48cea3662ca208e0a1529f374b1d982/src/main/java/za/ac/cput/school_management_grp33/factory/lookup/NameFactory.java#L14

**Comment by leokeke96** [comment]
Great done it i would like to know could i create an empty student address class in the domain to carry on smoothly with the repository, service and controller.

**Comment by ItsCurstin** [comment]
> Great done it i would like to know could i create an empty student address class in the domain to carry on smoothly with the repository, service and controller.

Yes that's fine yea, although you might not be able to because you need the attributes for repo, service and controller

**Comment by ItsCurstin** [comment]
After you update the Address entity, the AddressFactory should also be updated.

> Mandatory attributes of Address: streetNumber, StreetName, postalCode, city.

This is in the brief, please make sure you review the brief. So `unitNumber` and `complexName` in the AddressFactory should use `StringUtility.setEmptyIfNull();`

https://github.com/CurstinJR/school-management-grp33/blob/73f976f4678390965a9065781cbb187340f54c2e/src/main/java/za/ac/cput/school_management_grp33/factory/lookup/AddressFactory.java#L16-L17
